name: InstagramClone Builder

on:
  pull_request:
    branches:
      - 'master'


jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew build

      - name: Build Release AAB
        id: build_release
        run: ./gradlew bundleRelease

      - name: Sign Release AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_FILE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}' > service_account.json

      - name: Publish to Google Play (BETA)
        id: publish
        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJson: service_account.json
            packageName: com.hashconcepts.moneytracker
            releaseFile: app/build/outputs/bundle/release/app-release.aab
            track: beta
            inAppUpdatePriority: 4
            whatsNewDirectory: whatsnew/
            mappingFile: app/build/outputs/mapping/release/mapping.txt
            debugSymbols: app/intermediates/merged_native_libs/release/out/lib

      - name: Tag Release
        run: |
          version_name=${GITHUB_REF##*/}
          echo "Tagging release with tag $version_name"
          git tag $version_name release/$version_name
          git push origin --tags

  lint-check:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Lint check
        run: ./gradlew lint

      - name: Generate lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint_report.html
          path: app/build/reports/lint-result-debug.html

  unit-test:
    name: Unit Test
    needs: [ lint-check ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Execute unit test
        run: ./gradlew test --stacktrace

      - name: Generate test report
        uses: actions/upload-artifact@v2
        with:
          name: test_report.html
          path: app/build/reports/test/test-result-debug.html