name: InstagramClone Builder

on:
  pull_request:
    branches:
      - 'master'


jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Decode Keystore File
        id: decode_keystore_file
        uses: timheuer/base64-to-file@v1.1
        with:
            fileDir: './secrets'
            fileName: 'HashConceptsKey.jks'
            encodedString: ${{ secrets.SIGNING_KEY_FILE }}

      - name: Decode Google Play API Key
        id: decode_google_play_api_file
        uses: timheuer/base64-to-file@v1.1
        with:
            fileDir: './secrets'
            fileName: 'google-play-api-key.json'
            encodedString: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}

      - name: Build with gradle
        run: ./gradlew build

      - name: Build Release AAB
        id: build_release
        run: ./gradlew bundleRelease

      - name: Build & publish to Google Play (BETA)
        id: publish_to_play_store
        run: ./gradlew
          -PANDROID_PUBLISHER_CREDENTIALS="../${{ steps.decode_google_play_api_file.outputs.filePath }}"
          -PSIGNING_JKS_FILE_PATH="../${{ steps.decode_keystore_file.outputs.filePath }}"
          -PSIGNING_KEYSTORE_PASSWORD=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          -PSIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}
          -PSIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}
          publishBundle --max-workers 1




  lint-check:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Lint check
        run: ./gradlew lint

      - name: Generate lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint_report.html
          path: app/build/reports/lint-result-debug.html


  unit-test:
    name: Unit Test
    needs: [ lint-check ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Execute unit test
        run: ./gradlew test --stacktrace

      - name: Generate test report
        uses: actions/upload-artifact@v2
        with:
          name: test_report.html
          path: app/build/reports/test/test-result-debug.html